import { v4 as uuidv4 } from "uuid";

export const playlists = [
  {
    id: uuidv4(),
    title: "Shape of You",
    singer: ["Ed Sheeran"],
    album: "÷ (Divide)",
    played: 0,
    url: "https://open.spotify.com/track/7qiZfU4dY1lWllzX7mPBI3",
  },
  {
    id: uuidv4(),
    title: "Someone Like You",
    singer: ["Adele"],
    album: "21",
    played: 0,
    url: "https://open.spotify.com/track/4kflIGfjdZJW4ot2ioixTB",
  },
  {
    id: uuidv4(),
    title: "Blinding Lights",
    singer: ["The Weeknd"],
    album: "After Hours",
    played: 0,
    url: "https://open.spotify.com/track/0VjIjW4GlUZAMYd2vXMi3b",
  },
  {
    id: uuidv4(),
    title: "Uptown Funk",
    singer: ["Mark Ronson", "Bruno Mars"],
    album: "Uptown Special",
    played: 0,
    url: "https://open.spotify.com/track/32OlwWuMpZ6b0aN2RZOeMS",
  },
  {
    id: uuidv4(),
    title: "Bohemian Rhapsody",
    singer: ["Queen"],
    album: "A Night at the Opera",
    played: 0,
    url: "https://open.spotify.com/track/7tFiyTwD0nx5a1eklYtX2J",
  },
  {
    id: uuidv4(),
    title: "Imagine",
    singer: ["John Lennon"],
    album: "Imagine",
    played: 0,
    url: "https://open.spotify.com/track/3YRCj8LDU3vS3CfjbLsAe7",
  },
  {
    id: uuidv4(),
    title: "Billie Jean",
    singer: ["Michael Jackson"],
    album: "Thriller",
    played: 0,
    url: "https://open.spotify.com/track/5ChkMS8OtdzJeqyybCc9R5",
  },
  {
    id: uuidv4(),
    title: "Don't Start Now",
    singer: ["Dua Lipa"],
    album: "Future Nostalgia",
    played: 0,
    url: "https://open.spotify.com/track/6WrI0LAC5M1Rw2MnX2ZvEg",
  },
  {
    id: uuidv4(),
    title: "Rolling in the Deep",
    singer: ["Adele"],
    album: "21",
    played: 0,
    url: "https://open.spotify.com/track/1CkvWZme3pRgbzaxZnTl5X",
  },
  {
    id: uuidv4(),
    title: "All of Me",
    singer: ["John Legend"],
    album: "Love in the Future",
    played: 0,
    url: "https://open.spotify.com/track/3U4isOIWM3VvDubwSI3y7a",
  },
];